### ISSUE TITLE
TypeError: pg.connect is not a function

### ISSUE THREAD

**Issue by HeXY0515** [JohnLonginotto/SeQC#12]
Hi, 
There is an error after I type  "node SeQC.js.py":/Users/holly/Desktop/SeQC-master/SeQC.js.py:1237
    pg.connect(postgresConnection, function(err, client, done) {
       ^

TypeError: pg.connect is not a function
    at Object.<anonymous> (/Users/holly/Desktop/SeQC-master/SeQC.js.py:1237:8)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

I cannot understand this error and could you please help me out?

**Comment by JohnLonginotto** [comment]
Hi HeXY0515! Sorry for the extremely long delay in replying, i'll try and be quicker

It sounds like you don't have postgres for nodejs installed, or it's been updated and now no longer works with my software. I'll have a look at this tomorrow and get back to you :)

**Comment by HeXY0515** [comment]
Hi, thanks for replying and have you check this?  Would you like to provide a user guide for SeQC? I think it will be better to understand and use it with a guide file. Waiting for your replying~
